car = ['GESTWASH', 'ZMOV', 'NORAUTO']

gym = ['DESPORTIVO']

food = ['RESTAURANTES', 'RESTAURANTE', 'COMIDA', 'COMIDAS', 'REFEIÇÃO', 'REFEIÇÕES', 'FOOD', 'PASTELARIA', 'PADARIA', 'RESTAURAÇÂO', 'IKEA']

education = ['ESCOLA', 'EDUCAÇÃO', 'EDUCACAO', 'CURSO', 'FORMAÇÃO', 'EDUCATION']

health = []

transportation = ['TRANSPORTES', 'RODONORTE', 'FERTAGUS']

hairdress = ['CABELEIREIRO', 'CABELEIREIROS', 'CABELEIREIRA', 'CABELO']

vet = ['VETERINÁRIA', 'VETERINÁRIO', 'VETERINÁRIAS', 'VETERINÁRIOS', 'PETS']